version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=value
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://cloud:cloud@nicol20-cluster.emeo9pd.mongodb.net/test
      - MONGO_DB_NAME=test
      - REDIS_URI=rediss://default:AVNS_-brQ-a_DJHG0BACfWtW@redis-1521426b-student-1fff.aivencloud.com:23746
      